// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: esphomeLvglGui

#ifndef _ESPHOMELVGLGUI_UI_H
#define _ESPHOMELVGLGUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_localLabel;
void ui_event_page2Button(lv_event_t * e);
extern lv_obj_t * ui_page2Button;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_iPLabel;
extern lv_obj_t * ui_weatherLabel;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_chineseFont);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
