// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: esphomeLvglGui

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_localLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_localLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_localLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_localLabel, -136);
    lv_obj_set_y(ui_localLabel, -104);
    lv_obj_set_align(ui_localLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_localLabel, "地址");
    lv_obj_set_style_text_font(ui_localLabel, &ui_font_chineseFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_page2Button = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_page2Button, 55);
    lv_obj_set_height(ui_page2Button, 24);
    lv_obj_set_x(ui_page2Button, 80);
    lv_obj_set_y(ui_page2Button, 141);
    lv_obj_set_align(ui_page2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_page2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_page2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 374);
    lv_obj_set_y(ui_Spinner1, -18);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Arc5 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc5, 150);
    lv_obj_set_height(ui_Arc5, 150);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_page2Button, ui_event_page2Button, LV_EVENT_ALL, NULL);

}
